name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python -m pip install "copier>=8.0.0"

      - name: Execute the template
        run: |
          set -eux
          mkdir dummy
          python -m copier copy -a .copier-answer.vscode.yml -l --vcs-ref HEAD --UNSAFE . dummy
          cat .copier-answer.vscode.yml
          pushd dummy
